// <auto-generated />
using DuAn1.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DuAn1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251127035518_UpdateSeedProducts")]
    partial class UpdateSeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DuAn1.model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Điện thoại màn hình gập",
                            NameProduct = "Galaxy Fold7"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Điện thoại Apple mới nhất",
                            NameProduct = "iPhone 17"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Điện thoại giá rẻ cấu hình cao",
                            NameProduct = "Xiaomi 15"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Điện thoại gaming mạnh mẽ",
                            NameProduct = "RedMagic 10 Pro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
